### ISSUE TITLE
有没有postcss8的适配windicss的方案

### ISSUE THREAD

**Issue by Miofly** [viarotel/vue-uniapp-cli#1]
比如最新的 vite + vue3 + uniapp 的架构如何集成 windicss

**Comment by viarotel** [comment]
uniapp 官方有 vite 版本
windicss 默认也有 postcss8 集成选项
动手能力强的话可以自己集成 晚点我也会出一个 vite 版本的集成框架

**Comment by Miofly** [comment]
> uniapp 官方有 vite 版本 windicss 默认也有 postcss8 集成选项 动手能力强的话可以自己集成 晚点我也会出一个 vite 版本的集成框架

https://github.com/Miofly/vue3-vite-uniapp 我搭了一个简易的一个是windicss一个是Pinia在小程序都不支持

**Comment by viarotel** [comment]
首先 vite 用于生产还是有些问题 特别是小程序 还不能很好的和官方ide集成 还有许多坑需要填
其次小程序并不支持的一些语法过滤掉就好了 可以参考本项目 configs/windicss/uniapp 中的配置
