### ISSUE TITLE
sass有问题哦

### ISSUE THREAD

**Issue by kingsofish** [viarotel/vue-uniapp-cli#2]
Syntax Error: ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'additionalData'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }

npm install 
npm run serve

**Comment by viarotel** [comment]
已修复 v1.0.3

**Comment by kingsofish** [comment]
目前启动没问题了~但是在浏览器打开会报错。试了一下刷新页面就会出现报错，随机性出现，有时又是好的。

**Comment by viarotel** [comment]
> 目前启动没问题了~但是在浏览器打开会报错。试了一下刷新页面就会出现报错，随机性出现，有时又是好的。

我这里没有复现 使用什么浏览器 是否可以提供截图

**Comment by kingsofish** [comment]
![image](https://user-images.githubusercontent.com/19761833/147043354-d0387f2e-230b-425a-a704-49c93066415a.png)谷歌浏览器；很神奇的一个问题，随机出现，有时又是好的，我没改动过代码

**Comment by kingsofish** [comment]
![image](https://user-images.githubusercontent.com/19761833/147043833-d3303cbd-e551-4545-8cb2-7fe6e2d6b9e6.png)
这里没有任何报错提示，只有浏览器上有

**Comment by kingsofish** [comment]
以为是浏览器缓存问题，用无痕模式，刷新多次，还是出现。

**Comment by viarotel** [comment]
把 node_modules 和 yarn.lock 以及 package-lock.json 都删掉 重新安装依赖 再试试

**Comment by viarotel** [comment]
node 版本号是多少?

**Comment by kingsofish** [comment]
![image](https://user-images.githubusercontent.com/19761833/147045024-67d6cb51-0b8f-4bdc-a662-5bfef463fedd.png)

我貌似找到原因了，刚刚把这个占用的进程关闭了就没事了，没想到这个能影响，打扰了，谢谢！

**Comment by kingsofish** [comment]
这是昨天还有问题的那个启动项，一直没关，结果影响了今天的运行。又发现一个坑

**Comment by viarotel** [comment]
> 这是昨天还有问题的那个启动项，一直没关，结果影响了今天的运行。又发现一个坑

解决了就行 感兴趣的话点个star再走 防止迷路

**Comment by kingsofish** [comment]
又有问题了。。我把node_modules删了重新npm install，又出现这个问题了
![image](https://user-images.githubusercontent.com/19761833/147527541-6f7af6c8-66c5-4016-a766-2c26df31ff44.png)

![image](https://user-images.githubusercontent.com/19761833/147527560-f6277475-43f6-4f29-8fbf-edc6d1fc17b6.png)

![image](https://user-images.githubusercontent.com/19761833/147527570-7b884ae4-dade-4a7d-99a9-a6a4375d8f35.png)

node -v
v14.16.0

npm -v
6.14.11

**Comment by kingsofish** [comment]
重新从git拉下来，npm install后，也是这个样子。麻烦看看

**Comment by kingsofish** [comment]
将    "sass": "^1.43.4", "sass-loader": "^10.2.0"删除，换成低版本的 node-sass@4.14.1， 问题解决。sass的版本问题真的操蛋

**Comment by kingsofish** [comment]
> 将 "sass": "^1.43.4", "sass-loader": "^10.2.0"删除，换成低版本的 node-sass@4.14.1， 问题解决。sass的版本问题真的操蛋

看来还不是这个问题。。又出现了

**Comment by kingsofish** [comment]
> > 将 "sass": "^1.43.4", "sass-loader": "^10.2.0"删除，换成低版本的 node-sass@4.14.1， 问题解决。sass的版本问题真的操蛋
> 
> 看来还不是这个问题。。又出现了

安装了node-sass，再安装一下sass-loader，项目就跑不了了。
然后把sass-loader删除，项目还是跑不了了。
删除node_modules、package-lock.json、package.json中的sass-loader删除，在重新npm i，又可以跑了。

早有耳闻sass玩意很毒。。今天总算体会到了。。。如果是团队合作估计会很多版本兼容问题。。这玩意必须的列入黑名单...
